spring: # 主要用来存放不同环境差异化配置，包括ftp地址、数据库连接等
  profiles: test
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/HeiMa?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

