spring: # 主要用来存放不同环境差异化配置，包括ftp地址、数据库连接等
  profiles: prod
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.130.37:3306/china_steet_data?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
